# This workflow will build a Angular project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Angular CI/CD

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  dev-app-name: bharathikannan-h0epbtb4h0bshhfe.japaneast-01
  AZURE_WEBAPP_PACKAGE_PATH: "."

jobs:

  deploy_dev:
    runs-on: ubuntu-latest
    
    environment:
      name: BHARATHI_DEV
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install dependencies
        run: npm install
      - name: Build Dev
        run: ng build --configuration=dev
      - name: Deploy Dev
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.dev-app-name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist  